### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by RocketSurgeon214** [chanzer0/NBA-TopShot-Chrome-Extension#10]
Thanks for putting this together.  Are you still planning on getting the monitoring set back up?  Also, when I click on the extension when I'm in Chrome, it won't let me click on the "Options" drop down.  Any help is appreciated and thanks again for your hard work.

**Comment by chanzer0** [comment]
There shouldn't be any need to click the extension in the browser tray, all the extension information and actions will be on-screen when you refresh a listing page.

Monitoring is currently active, but only for price floors.
