### ISSUE TITLE
Sorting issue - my resolution

### ISSUE THREAD

**Issue by rpierucci** [chanzer0/NBA-TopShot-Chrome-Extension#11]
Hey there, I was not able to get your code to work properly with the sorting. I kept getting an undefined error on line 96 of pricesort.js, saying something about "could not do a replace on undefined". Upon looking at the code, I see that the dropdown option[0] is a string of text rather than an actual price. To fix this issue I went ahead and started the newList being built from i = 1 instead of i = 0 on line 72. Otherwise I love the tool and I was wanting to build something just like this until I found your github. Thanks for that!

**Comment by chanzer0** [comment]
Hi rpierucci, 

Recently the site had updated to include an option in their select menu called "SELECT SERIAL NUMBER". This broke the extension, as you found. I pushed an update to fix this, however, your solution also works! Very resourceful!
