### ISSUE TITLE
Is it allowed to use this extension, regarding latest ToS update?

### ISSUE THREAD

**Issue by GrigoryEvko** [chanzer0/NBA-TopShot-Chrome-Extension#12]
@chanzer0 
Good day. How do you think, is it allowed to use this extension for now? Can the top shot site actually discern, whether I use some extra JavaScript code or no? Thanks.

**Comment by matthewfdaniels** [comment]
I feel like in theory it's possible, since they could just query the dom and see if any elements have been injected. That said, many sites manipulate the dom, including screen readers, ad blockers, etc. I feel like it'd be hard for them to separate the two.

**Comment by chanzer0** [comment]
Hi, UTC10.

Given the most recent ToS updates for NBA Top Shot, I have removed the price monitoring script from the extension. However, the price sorting extension should be just fine as it is not a bot/script being used to purchase moments. As far as I can tell, they wouldn't be able to detect javascript on the client-side that simply modifies DOM elements.

I hope this clears up any concerns.

**Comment by GrigoryEvko** [comment]
Thanks!
