### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by creepyjeremy** [chanzer0/NBA-TopShot-Chrome-Extension#13]
Just installed this and haven't had a chance to play around with it much but the color coding seems to really improve the listing pages. I'm not sure how to use the monitoring feature but will continue to play around with it. Thanks for making this extension.

**Comment by chanzer0** [comment]
@creepyjeremy Hi Jeremy. Unfortunately, due to the updated Terms of Service, I no longer am supporting the price monitoring feature for this extension. Everything else should work just fine, however. 

Hope you're finding the extension useful,

Sean.
