### ISSUE TITLE
Not showing in moments screen

### ISSUE THREAD

**Issue by mreading2020** [chanzer0/NBA-TopShot-Chrome-Extension#14]
Does not seem to work for me. Some things are greyed out. attached screen snip and build below. 

Google Chrome is up to date
Version 89.0.4389.114 (Official Build) (64-bit)
![Untitlssssed](https://user-images.githubusercontent.com/67369344/114529444-879ca580-9c7c-11eb-9465-aa39f9a39cfc.png)

**Comment by chanzer0** [comment]
Hi, @mreading2020. Unfortunately, I have discontinued support for this extension as I have joined a full-time team dedicated to making NBA Top Shot tools and features. 

I hope that in the near future you will be able to use these tools to their fullest potential. Until then, there are currently no plans for updating the current repository.

All the best,
Sean.

**Comment by mreading2020** [comment]
Oh ok.

What version did it last support.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
