### ISSUE TITLE
Amazing Tools

### ISSUE THREAD

**Issue by SlicedBread13** [chanzer0/NBA-TopShot-Chrome-Extension#2]
If you are in to NBA Top Shots, this extension is a MUST!  I have already had success using the extension and I will not go without it before making a purchase in the marketplace.  Thanks again!

**Comment by chanzer0** [comment]
Thank you so much, I love hearing success stories from my users! Stay tuned for future updates! Feel free to suggest any improvements or report issues you have.

Best Wishes,
Sean S.
