### ISSUE TITLE
Just awesome.

### ISSUE THREAD

**Issue by Dan1312** [chanzer0/NBA-TopShot-Chrome-Extension#4]
Great extension already with tons of potential. Excited to continue to use it and see it progress!

**Comment by chanzer0** [comment]
Thank you so much Dan. I'm so glad you are enjoying the extension so far. Don't be afraid to follow up with improvements you'd like to see that would make your workflow easier. If you run into any bugs, let me know and I'll be sure to fix them.

Sean S.

**Comment by Dan1312** [comment]
For sure man! And thank YOU!
