### ISSUE TITLE
Ignore certain serials

### ISSUE THREAD

**Issue by SneakBots** [chanzer0/NBA-TopShot-Chrome-Extension#6]
Hey dude! Love this extension a ton, especially the price monitor. Could we get a "ignore" feature on the monitor so glitched moments for sale don't cause the monitor to go off?

**Comment by chanzer0** [comment]
Yes, that's a good idea! While ideally these glitched listings should be fixed by the site, I think this is a good feature to have in the extension. I will add this to my backlog.

**Comment by chanzer0** [comment]
Closing as price monitoring is no longer supported by the new ToS
