### ISSUE TITLE
Suggestion: Dapper Confirm Option

### ISSUE THREAD

**Issue by whiteflavored** [chanzer0/NBA-TopShot-Chrome-Extension#7]
Hello chan!

Thought maybe this could be a possible "improvement" option in the future - but this already works 150% as is!

Example: let's say I am tracking coolcats and want to snipe a card that's "fat fingered" at $99 (when normal price is $300+). I understand about having the manual payment confirmation, (and that is needed!) but would there be a way to add a UI toggle "Confirm Purchase?" = yes/no so that when I do snipe a misprice I can buy it as fast as possible?

Confirming to go to dapper is one thing, but still SHOULD require manual confirmation anyways. But if the user wanted to auto run it, could that be an option moving forward?

You're awesome man! This works 150% as is and definitely a professional tool.

**Comment by chanzer0** [comment]
Adding a dapper buy is something I've considered, however, I don't quite feel comfortable having auto-purchase on as there may always be an issue or bug I overlook that could result in the bug buying for them when they didn't mean to.

So, just to be safe, I don't think I will add a dapper auto-buy option
